# Generated by Django 2.0.2 on 2018-02-20 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField(verbose_name='time edited')),
                ('note', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date project created')),
                ('song_key', models.CharField(max_length=100, null=True)),
                ('project_notes', models.CharField(max_length=600, null=True)),
                ('main_user', models.CharField(max_length=30, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=200)),
                ('instrument', models.CharField(max_length=200, null=True)),
                ('tempo', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('track_date', models.DateTimeField(verbose_name='track added date')),
                ('track_notes', models.CharField(max_length=600, null=True)),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audiogenie.Project')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audiogenie.Project'),
        ),
    ]
