# Generated by Django 2.0.2 on 2018-02-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiogenie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_img',
            field=models.ImageField(default='/static/audiogenie/img/project.jpg', upload_to='media/'),
        ),
    ]
