# Generated by Django 2.0.2 on 2018-02-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiogenie', '0003_auto_20180227_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(default='/static/audiogenie/img/project.jpg', upload_to='media/project_images/'),
        ),
    ]
