# Generated by Django 2.0.2 on 2018-02-27 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiogenie', '0004_auto_20180227_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiogenie.Project'),
        ),
    ]
