# Generated by Django 2.0.2 on 2018-02-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiogenie', '0005_auto_20180227_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(upload_to='media/project_images/'),
        ),
    ]
