# Generated by Django 2.0.2 on 2018-02-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiogenie', '0006_auto_20180227_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(default='/static/audiogenie/img/project.jpg', upload_to='media/project_images/'),
        ),
    ]
